### ISSUE TITLE
Todo for v0.13.0

### ISSUE THREAD

**Issue by ElPumpo** [ElPumpo/Win10Clean#8]
- [x] Merge `csharp-rewrite` to `master`
- [x] Fix update checker
- [x] Finish Fall ceators update stuff #7 
- [ ] ~~Get back tooltips! Kinda related to #4~~
